name: to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  lottie: ^3.3.2
  shared_preferences: ^2.5.4
  google_fonts: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^20.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/img/
    - assets/lotties/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-Bold.ttf
          weight: 700



